### ISSUE TITLE
Improve Text cropping Docs

### ISSUE THREAD

**Issue by JohnTParsons** [newscorp-ghfb/NewsKit#811]
# Description

Anything we could do to improve the docs or storybook around text cropping? eg Point to an old build of the capsize site (or scrape information from that) as the new site does not make as much sense.?

Look at most frequent FAQs for text crop, make sure these are addressed in the docs. 

Relevant Slack Thread - https://newsuktechnology.slack.com/archives/C024ZGQ2W8K/p1680617868065319

# Business Benefit/Value
Help brands like Dow Jones, avoid issues when upgrading from NewsKit 6.

# Acceptance Criteria

Go through the process, proposed update to docs, seek feedback from design 

- Update instructions in - https://newskit.co.uk/theme/theming/creating-a-theme/#createtheme-function , Could we also convert this page to TSX so the deep linking works
- https://newskit.co.uk/theme/foundation/fonts/#textcrop this page should be updated to point to the instructions on the create theme page.

**Comment by GeriReid** [comment]
Thanks @mstuartf, adapting the capsize interactive components so the output matches what NewsKit requires looks helpful. I'd suggest we leave it in the /creating-a-theme section if it follows the steps consumers need to go through to set up. Then link to it from [here](https://newskit.co.uk/theme/foundation/fonts/#textcrop):

<img width="676" alt="image" src="https://user-images.githubusercontent.com/39526800/234277134-420c509c-90bc-4a9b-b87b-1ea0b482feb3.png">

If you were setting up a theme would that seem logical?

**Comment by mstuartf** [comment]
Sounds sensible. Shall I mock that up using Newskit components and send it back to you for feedback?

**Comment by GeriReid** [comment]
Sounds good - thanks Mike

**Comment by mstuartf** [comment]
Hi @GeriReid, I've nested the text crop calculator on the theme page as mentioned above: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/811-text-crop-docs/theme/theming/creating-a-theme/

There are a few issues with the Select (i.e. unwanted focus outlines and page jumping) at the moment but it's ready for design review otherwise.

**Comment by GeriReid** [comment]
Thanks @mstuart, the calculator works well in-situ. 

- Really only adding a border radius to the focus outline and the page jumping on select that you highlighted not working for me - the rest looks good. 

- Suggest adding a space080 (48px) above the **1. Choose a font** heading to give it some space.


![image](https://user-images.githubusercontent.com/39526800/235138162-c9c1d377-a299-4eb3-a71a-d011baa85872.png)
- For the subhead here suggest: 
Create your own theme, or use one of the two NewsKit defaults.

I'll run this past the design team for feedback.

**Comment by GeriReid** [comment]
@mstuartf had feedback from Nathan on the dark theme, we lose the annotations on dark:

![image](https://user-images.githubusercontent.com/39526800/235173521-baa0bd0e-f7d0-40a2-a1e0-decbcc316a09.png)

Is it possible to theme this using our tokens...or not because it's a third party tool?

**Comment by nathanparris** [comment]
@mstuartf These colour tokens would be good to use and will theme correctly. 

![image](https://user-images.githubusercontent.com/108727455/235640922-8f168a20-46bb-4483-bd54-3388d4ccc977.png)

**Comment by mstuartf** [comment]
Thanks @nathanparris !

**Comment by mstuartf** [comment]
@nathanparris @GeriReid I've implemented your changes here: http://ncu-newskit-docs-pr.s3-website-eu-west-1.amazonaws.com/811-text-crop-docs/theme/theming/creating-a-theme/

**Comment by GeriReid** [comment]
Thanks for supplying the colour tokens @nathanparris, this is theming well now in dark.
@mstuartf looking good - I'm still getting a page jump on the font select, is this something you're able to address with the calculator in the page?

**Comment by mstuartf** [comment]
Thanks, @GeriReid 

There's a separate ticket to address the Select jump issue as it's not specific to this page.

**Comment by GeriReid** [comment]
@mstuartf - cheers, I'm a bit out of the loop on this one! Is this good to go for you @nathanparris?
